### ISSUE TITLE
播放视频拉伸的问题

### ISSUE THREAD

**Issue by luoyou592** [miaoyongjun/MVideo#5]
用最新mate20pro播放视频，画面被拉伸了，可否有优化

**Comment by mikaelzero** [comment]
这个库已经不准备维护了
可以查看 [YoutubeVideoSample](https://github.com/moyokoo/YoutubeVideoSample)
效果相似  而且扩展性更高 不过需要自行修改

另外拉伸问题是由TextureView造成的  可以查看[ResizeTextureView](https://github.com/maiwenchang/ArtPlayer/blob/master/artplayer-java/src/main/java/org/salient/artplayer/ResizeTextureView.java)

**Comment by luoyou592** [comment]
效果还是差很多哈，我再琢磨琢磨吧，有些视频不会拉宽，有些会，都不知视频问题还是啥，在其他手机又都一切正常

**Comment by mikaelzero** [comment]
新做了一个库  不知道有没有符合你的需求  暂时还未提供正式版本 可以参考
[DragDiooto](https://github.com/moyokoo/DragDiooto)
